config/routes.rb
Rails.application.routes.draw do
  get 'tester/index1'

  get 'tester/index2'

  get 'tester/index3'

  get 'tester/index4'

  get 'tester/index5'

  get 'tester/index6'

  get 'tester/index7'

  resources :contents
  devise_for :users

  resources :articles
  mount ActionCable.server => '/cable'

  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 3 }
	has_many :contents
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles, dependent: :destroy


  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index

	  @articles = Article.order(:title).all
	  rescue exc
      logger.error("No Articles! #{exc.message}")
      flash[:notice] = "There were no articles!"

  end

  def show
    @article = Article.find(params[:id])
    @articles= Article.includes(:contents).order(:title).all
  end

  def new
	  @article = Article.new
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def create
	  @article = Article.new(article_params)

	  if @article.save
	    redirect_to @article
	  else
	    render 'new'
	  end
  end

  def edit
	  begin
		  @article = Article.find(params[:id])
	  rescue Exception => exc
      logger.error("No Articles! #{exc.message}")
      flash[:notice] = "There were no articles!"
	  end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # has_many :title, through => :article, :order => 'article.title'
  # GET /contents
  # GET /contents.json
  def index
    begin
      @contents = Content.includes(:article).order(:title).all
	  rescue exc
      logger.error("No Articles! #{exc.message}")
      flash[:notice] = "There were no articles!"
	    raise exc
	  end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:title, :data, :article_id)
    end
end

app/controllers/tester_controller.rb
class TesterController < ApplicationController
  def index1
  end

  def index2
  end

  def index3
  end

  def index4
  end

  def index5
  end

  def index6
  end

  def index7
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

module DeviseHelper
  def devise_error_messages1!
    resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
  end

  def devise_error_messages2!
    resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/tester_helper.rb
module TesterHelper
end

app/views/articles/edit.html.erb
<% if current_user.admin? %>
  <h1>Edit Class</h1>
	<%= form_for (@article) do |f| %>

	  <% if @article.errors.any? %>
		  <div id="error_explanation">
		    <h2>
			    <%= pluralize(@article.errors.count, "error") %> prohibited
			    this article from being saved:
		    </h2>
		    <ul>
			  <% @article.errors.full_messages.each do |msg| %>
			    <li><%= msg %></li>
			  <% end %>
		    </ul>
		  </div>
	  <% end %>

	  <p>
		  <%= f.label "Class Name" %><br>
		  <%= f.text_field :title %>
	  </p>

	  <p>
		  <%= f.label "Content" %><br>
		  <%= f.text_area :text %>
	  </p>

	  <p>
		  <%= f.submit "Update Class", class: 'btn btn-success'%>
		  <%= link_to 'Back', articles_path , class: 'btn btn-primary' %>
	  </p>

	<% end %>
<% end %>

app/views/articles/index.html.erb
<% if current_user.admin? %>
  <p>
    <h1><strong>Teachers Dashboard</strong></h1>
  </p>
<% else %>
  <p>
    <h1><strong>Student Dashboard</strong></h1>
  </p>
<% end %>

<table>
  <tr>
    <th><h4>Class</h4></th>
  </tr>

 <%#= CHECKS FOR USER ADMIN PRIVELEGES AND THEN DISPLAYS APPROPRIATE CONTROLS %>
   <% if current_user.admin? %>

     <p>
	     <%= link_to 'Add New Class', new_article_path, class: 'btn btn-success' %>
	     <%= link_to 'View Class Contents', contents_path, class: 'btn btn-success' %>
	   </p>

    <% @articles.each do |article| %>
	     <tr>
	       <td><%= article.title %></td>
		     <td><%= link_to 'Show Class', article_path(article), class: 'btn btn-primary btn-sm' %></td>
		     <td><%= link_to 'Edit Class', edit_article_path(article), class: 'btn btn-info btn-sm'  %></td>
		     <td><%= link_to 'Delete Class', article_path(article), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure you want to delete the class?' } %></td>
	     </tr>
    <% end %>

  <% else %>

    <% @articles.each do |article| %>
	    <tr>
	      <td><%= article.title %></td>
		    <td><%= link_to 'Show Class', article_path(article), class: 'btn btn-primary btn-sm'  %></td>
	    </tr>
	<% end %>

<% end %>
</table>

app/views/articles/new.html.erb
<% if current_user.admin? %>

	<h1>New Class</h1>

	<%= form_for(@article) do |f| %>

	  <% if @article.errors.any? %>
		  <div id="error_explanation">
		    <h2>
			    <%= pluralize(@article.errors.count, "error") %> prohibited
			    this article from being saved:
		    </h2>
		    <ul>
			    <% @article.errors.full_messages.each do |msg| %>
			    <li><%= msg %></li>
			    <% end %>
		    </ul>
		  </div>
	  <% end %>
	 
	  <p>
		  <%= f.label "Class Name" %><br>
		  <%= f.text_field :title %>
	  </p>

	  <p>
		  <%= f.label "Content" %><br>
		  <%= f.text_area :text %>
	  </p>

	  <p>
		  <%= f.submit "Create Class", class: 'btn btn-success' %>
		  <%= link_to 'Back', articles_path , class: 'btn btn-primary' %>
	  </p>

	<% end %>
<% end %>

app/views/articles/shared/_links.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Edit Account", edit_registration_path(resource_name), class: 'btn btn-primary' %><br />
<% end -%>

app/views/articles/show.html.erb
<p>
  <h1><%= @article.title %></h1>
</p>

<p>
  <% if current_user.admin? %>
    <%= link_to 'Edit Class', edit_article_path(@article), class: 'btn btn-success'%>
  <% end %>
</p>

<p>
  <strong>Content:</strong>
</p>

<p>
  <%= @article.text %>
</p>

<p>
  <% @article.contents.order :title %>
  <% @article.contents.each do |c| %>
	  <p>
	    <strong><%= c.title %></strong>
	  </p>
	  <p>
	    <%= c.data %>
	  </p>
  <% end %>
</p>

<p>
  <%= link_to 'Back', articles_path, class: 'btn btn-primary'  %>
</p>

app/views/contents/_form.html.erb
<%= form_for(content) do |f| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Class" %>
    <%= f.select :article_id, [['History','1'],['Science','2'],['Mathematics','3'],['Arts','4']] %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label "Content" %>
    <%= f.text_field :data %>
  </div>

  <div class="actions">
	  <%= f.submit%>
    <%= link_to 'Back', contents_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>
<p>
  <%= render 'form', content: @content %>
</p>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contents</h1>
<%= link_to 'New Content', new_content_path, class: 'btn btn-success' %>
<p></p>
<table>
  <thead>
    <tr>
	    <th>Class</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @contents.each do |content| %>
		  <tr>
		    <td><%#= content.article.title %></td>
        <td><%= content.title %></td>
        <td><%= link_to 'Show', content, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_content_path(content), class: 'btn btn-info' %></td>
        <td><%= link_to 'Delete Content', content, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', articles_path, class: 'btn btn-primary' %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path, class: 'btn btn-primary' %>

app/views/contents/show.html.erb
<p>
  <strong>Class:</strong>
  <%= @content.article.title %>
</p>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @content.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @content.data %>
</p>

<%= link_to 'Edit', edit_content_path(@content), class: 'btn btn-success' %>
<%= link_to 'Back', contents_path, class: 'btn btn-primary'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Black Bored</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-inverse">
      <%= link_to 'Black Bored', root_path, class: 'navbar-brand' %>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav pull-xs-right">
          <li class="nav-item">
            <span class="text-muted">Logged in as <strong><%= current_user.name %></strong></span>
          </li>
          <li class="nav-item active">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        </ul>
      <% end %>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <div class="container">
      </div>
    </footer>
  </body>

</html>

app/views/tester/index1.html.erb
<h1>Tester#index1</h1>
<p>Find me in app/views/tester/index1.html.erb</p>

app/views/tester/index2.html.erb
<h1>Tester#index2</h1>
<p>Find me in app/views/tester/index2.html.erb</p>

app/views/tester/index3.html.erb
<h1>Tester#index3</h1>
<p>Find me in app/views/tester/index3.html.erb</p>

app/views/tester/index4.html.erb
<h1>Tester#index4</h1>
<p>Find me in app/views/tester/index4.html.erb</p>

app/views/tester/index5.html.erb
<h1>Tester#index4</h1>
<p>Find me in app/views/tester/index4.html.erb</p>

app/views/tester/index6.html.erb
<h1>Tester#index4</h1>
<p>Find me in app/views/tester/index4.html.erb</p>

app/views/tester/index7.html.erb
<h1>Tester#index4</h1>
<p>Find me in app/views/tester/index4.html.erb</p>